
# Site settings
title: "q5ca's world"
description: >- # this means to ignore newlines until "baseurl:"
  Q5Ca's world CTF CVE Q5Ca q5ca q5ca q5ca q5ca q5ca q5ca
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://q5ca.pw" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
highlighter: rouge
plugins:
  - jekyll-feed

  - jekyll-seo-tag
  - jekyll-sitemap
permalink: /:categories/:title-:month-:day-:year.html
environment: development
defaults:
  -
    scope:
      path: "" 
    values:
      lang: "vi"