
# Site settings
title: "q5ca's world"
description: >- # this means to ignore newlines until "baseurl:"
  q5ca's world CTF CVE q5ca q5ca q5ca q5ca q5ca q5ca q5ca
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
permalink: /:categories/:title-:month-:day-:year.html
environment: production